redir-port: 1182
tproxy-port: 5000
mixed-port: 1080
allow-lan: true
log-level: silent
find-process-mode: off
ipv6: false
external-ui: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
external-controller: 0.0.0.0:9090

profile:
  store-selected: true

sniffer:
  enable: true
  parse-pure-ip: true
  sniff:
    HTTP:
    TLS:
    QUIC:

proxies:
- name: "GERMANY"
  type: vless
  server: '****'
  port: 8443
  uuid: '****'
  udp: true
  tls: true
  servername: 'yahoo.com'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: '****'
    short-id: 'd0'
- name: "RUSSIA"
  type: vless
  server: '****'
  port: 8443
  uuid: '****'
  udp: true
  tls: true
  servername: 'yahoo.com'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: '****'
    short-id: 'd0'
- name: "NIDERLAND"
  type: vless
  server: '****'
  port: 8443
  uuid: '****'
  udp: true
  tls: true
  servername: 'yahoo.com'
  skip-cert-verify: false
  client-fingerprint: 'chrome'
  network: 'tcp'
  reality-opts:
    public-key: '****'
    short-id: 'd0'

proxy-groups:
  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies:
      - REJECT
      - PASS
  - name: TikTok
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    include-all: true
    proxies:
      - DIRECT

  - name: JetBrains
    type: select
    icon: https://github.com/cazmusw/MihomoInstallKenetic/blob/main/icons/jetbrains.png
    include-all: true
    proxies:
      - DIRECT

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies:
      - DIRECT

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies:
      - DIRECT

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies:
      - DIRECT

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    include-all: true
    proxies:
      - DIRECT

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    include-all: true
    proxies:
      - DIRECT

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    exclude-filter: 🇷🇺
    proxies:
      - DIRECT

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies:
      - DIRECT

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies:
      - DIRECT

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    include-all: true
    proxies:
      - DIRECT

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    exclude-filter: 🇷🇺
    proxies:
      - DIRECT

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies:
      - DIRECT

  - name: Amazon
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Amazon.png
    include-all: true
    proxies:
      - DIRECT


  - name: Instagram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Instagram.png
    include-all: true
    proxies:
      - DIRECT

  - name: Mozilla
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Star.png
    include-all: true
    proxies:
      - DIRECT

  - name: Github
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Star.png
    include-all: true
    proxies:
      - DIRECT


rule-providers:

  discord-voice-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/cazmusw/MihomoInstallKenetic/raw/refs/heads/main/rulesets/discord-voice-ip-history.mrs
    path: ./rule-providers/discord-voice-ips.mrs
    interval: 43200
  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/cazmusw/MihomoInstallKenetic/raw/refs/heads/main/rulesets/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 43200
  amazon-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/cazmusw/MihomoInstallKenetic/raw/refs/heads/main/rulesets/amazon.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 43200
  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 43200
  zkeen_domains_youtube:
    type: http
    behavior: classical
    format: text
    url: https://github.com/toneywhitez/zkeen_rules/releases/latest/download/youtube.list
    path: ./rule-providers/zkeen_domains_youtube.list
    interval: 86400
  zkeen_ip_ru:
    type: http
    behavior: classical
    format: text
    url: https://github.com/toneywhitez/zkeen_rules/releases/latest/download/ru_ips.list
    path: ./rule-providers/zkeen_ip_ru.list
    interval: 86400
rules:

  - AND,((NOT,((RULE-SET,zkeen_ip_ru,no-resolve))),(NETWORK,UDP),(DST-PORT,443)),QUIC # Блокировка QUIC на ВНЕ РУ (!Zkeen RU IPs)


  - RULE-SET,zkeen_domains_youtube,YouTube

  - GEOSITE,oracle,JetBrains

  - GEOSITE,mozilla,Mozilla
  - GEOSITE,github,Github

  - GEOSITE,steam,Steam
  - GEOSITE,spotify,Spotify
  - GEOSITE,jetbrains,JetBrains
  - GEOSITE,jetbrains-ai,JetBrains

  - GEOSITE,meta,Meta
  - GEOSITE,reddit,Reddit
  - GEOSITE,tiktok,TikTok
  - GEOSITE,instagram,Instagram


  - GEOSITE,twitch,Twitch
  - GEOSITE,twitter,Twitter

  - GEOSITE,category-ai-!cn,AI

  - OR,((GEOSITE,discord),(RULE-SET,discord-voice-ips,no-resolve)),Discord
  - OR,((GEOSITE,telegram),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((GEOSITE,cloudflare),(RULE-SET,cloudflare-ips)),Cloudflare
  - OR,((GEOSITE,amazon),(RULE-SET,amazon-ips)),Amazon
  - MATCH,DIRECT
